INSERT INTO MEMBERS (MEMBER_ID, MEMBER_NAME, PASSWORD, ROLES)
    VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'ADMIN');
INSERT INTO MEMBERS (MEMBER_ID, MEMBER_NAME, PASSWORD, ROLES)
    VALUES (2, 'tipsyboy', '$2a$10$Xo1qLt8df/PCCwn1V8/VH.NMOzN0TPoAeqBOR4mF/QXVgi2MtR/iS', 'MEMBER');